### PR TITLE
SW-695

### PR DESCRIPTION
**Pull request by kevinsuepirus**

### CODE REVIEW

**Comment by jason-at-epirus** [comment]
The only contribution I'm likely to make to this PR is the nitpick that in the block diagrams in the README, it should be "Function Generator" rather than "Signal Generator" ("Func Gen" rather than "Sig Gen"). :)

**Comment by jason-at-epirus** [comment]
I take that back.  When you start working on the API, then I could be helpful.

**Comment by kevinsuepirus** [comment]
Hello World! officially out of vivado territory
image

Now to write some basic TCL scripts to burn down risk of inability to bringup in lab, confirm IRP functions, observe output signals on ILA

**Comment by kevinsuepirus** [comment]
v0.0.1 tagged.

**Comment by kevinsuepirus** [comment]
tagged v0.0.2 reflecting gate en fix

**Pull request merged**
